name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.2.0
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive .
      - run: black --check . || true
      - run: codespell
      - run: flake8 . --count --max-complexity=10 --max-line-length=120 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - uses: Gr1N/setup-poetry@v9
      - run: poetry install
      - run: mypy --install-types --non-interactive . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
